### ISSUE TITLE
Output of point selection/reduction algorithms

### ISSUE THREAD

**Issue by gtouya** [LostInZoom/cartagen#11]
Right now the point selection algorithms deliver a new geopandas Geodataframe as output, with only the selected/reduced point set. In a system where these algorithms are chained in trial-error fashion, it is more practical to keep all features in the output Geodataframe, with an additional column indicating if the feature is selected or not.

**Comment by jberli** [comment]
This is indeed a good point, this behavior will be implemented in the 1.0.1

**Comment by jberli** [comment]
Point reduction methods have been fixed and will be included in next release f9033ad5910636d0028b13d78a51adf71b383835
